# Generated by Django 4.2.6 on 2023-12-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='sal',
            field=models.IntegerField(null=True),
        ),
    ]
